// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice =
  | ContactSectionSlice
  | OurValuesSlice
  | OurMissionSlice
  | OurStorySlice
  | HeroAboutSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomePageDocumentDataSlicesSlice =
  | PresentersTeamSlice
  | ProgramsListSlice
  | HeroStatsWithActionsSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type JuncoNewsDocumentDataSlicesSlice =
  | ArticlesGridSlice
  | FeaturedArticlesSlice;

/**
 * Content for junco_news documents
 */
interface JuncoNewsDocumentData {
  /**
   * Slice Zone field in *junco_news*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: junco_news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<JuncoNewsDocumentDataSlicesSlice> /**
   * Meta Title field in *junco_news*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: junco_news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *junco_news*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: junco_news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *junco_news*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: junco_news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * junco_news document from Prismic
 *
 * - **API ID**: `junco_news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JuncoNewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JuncoNewsDocumentData>,
    "junco_news",
    Lang
  >;

/**
 * Content for News Article documents
 */
interface NewsArticleDocumentData {
  /**
   * Título do Artigo field in *News Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digite o título principal...
   * - **API ID Path**: news_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtítulo field in *News Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Breve descrição ou subtítulo...
   * - **API ID Path**: news_article.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Imagem Destacada field in *News Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"mobile" | "tablet">;

  /**
   * Resumo/Excerpt field in *News Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Breve resumo do artigo para SEO e cards...
   * - **API ID Path**: news_article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Autor field in *News Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do autor
   * - **API ID Path**: news_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Data de Publicação field in *News Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news_article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publication_date: prismic.DateField;

  /**
   * Categoria field in *News Article*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Selecione uma categoria
   * - **API ID Path**: news_article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Tecnologia"
    | "Esportes"
    | "Política"
    | "Economia"
    | "Cultura"
    | "Internacional"
    | "Saúde"
    | "Educação"
  >;

  /**
   * Tags field in *News Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: tag1, tag2, tag3
   * - **API ID Path**: news_article.tags
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;

  /**
   * Tempo de Leitura (minutos) field in *News Article*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5
   * - **API ID Path**: news_article.reading_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  reading_time: prismic.NumberField;

  /**
   * Artigo em Destaque field in *News Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: news_article.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Ordem de Destaque field in *News Article*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: news_article.featured_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  featured_order: prismic.SelectField<"none" | "1" | "2" | "3" | "4"> /**
   * Meta Título field in *News Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título para SEO (máx. 60 caracteres)
   * - **API ID Path**: news_article.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Descrição field in *News Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Descrição para SEO (máx. 160 caracteres)
   * - **API ID Path**: news_article.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Open Graph Image field in *News Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_article.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never> /**
   * Conteudo field in *News Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_article.body
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  body: prismic.RichTextField;
}

/**
 * News Article document from Prismic
 *
 * - **API ID**: `news_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsArticleDocumentData>,
    "news_article",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | HomePageDocument
  | JuncoNewsDocument
  | NewsArticleDocument;

/**
 * Item in *ArticlesGrid → Default → Primary → Available Categories*
 */
export interface ArticlesGridSliceDefaultPrimaryFilterCategoriesItem {
  /**
   * Category Name field in *ArticlesGrid → Default → Primary → Available Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tecnologia
   * - **API ID Path**: articles_grid.default.primary.filter_categories[].category_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_name: prismic.KeyTextField;

  /**
   * Category Slug field in *ArticlesGrid → Default → Primary → Available Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: tecnologia
   * - **API ID Path**: articles_grid.default.primary.filter_categories[].category_slug
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_slug: prismic.KeyTextField;
}

/**
 * Primary content in *ArticlesGrid → Default → Primary*
 */
export interface ArticlesGridSliceDefaultPrimary {
  /**
   * Section Title field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Todas as Notícias
   * - **API ID Path**: articles_grid.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Articles per Page field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 12
   * - **API ID Path**: articles_grid.default.primary.articles_per_page
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  articles_per_page: prismic.NumberField;

  /**
   * Show Filters field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: articles_grid.default.primary.show_filters
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_filters: prismic.BooleanField;

  /**
   * Show Search field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: articles_grid.default.primary.show_search
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_search: prismic.BooleanField;

  /**
   * Default Sort Order field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Escolha a ordenação
   * - **API ID Path**: articles_grid.default.primary.default_sort
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  default_sort: prismic.SelectField<
    | "publication_date_desc"
    | "publication_date_asc"
    | "title_asc"
    | "title_desc"
  >;

  /**
   * Available Categories field in *ArticlesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_grid.default.primary.filter_categories[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  filter_categories: prismic.GroupField<
    Simplify<ArticlesGridSliceDefaultPrimaryFilterCategoriesItem>
  >;
}

/**
 * Default variation for ArticlesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Articles grid with filters, search, and pagination
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticlesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticlesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticlesGrid*
 */
type ArticlesGridSliceVariation = ArticlesGridSliceDefault;

/**
 * ArticlesGrid Shared Slice
 *
 * - **API ID**: `articles_grid`
 * - **Description**: Articles grid with filtering and pagination
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticlesGridSlice = prismic.SharedSlice<
  "articles_grid",
  ArticlesGridSliceVariation
>;

/**
 * Item in *ContactSection → Default → Primary → Social Links*
 */
export interface ContactSectionSliceDefaultPrimarySocialLinksItem {
  /**
   * Platform field in *ContactSection → Default → Primary → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Escolha a plataforma
   * - **API ID Path**: contact_section.default.primary.social_links[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    | "Instagram"
    | "Twitter"
    | "LinkedIn"
    | "Facebook"
    | "YouTube"
    | "TikTok"
    | "Website"
  >;

  /**
   * URL field in *ContactSection → Default → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL da rede social
   * - **API ID Path**: contact_section.default.primary.social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Entre em Contato
   * - **API ID Path**: contact_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Entre em contato conosco...
   * - **API ID Path**: contact_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Email field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contato@junco.tv
   * - **API ID Path**: contact_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +55 (11) 99999-9999
   * - **API ID Path**: contact_section.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Social Links field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<ContactSectionSliceDefaultPrimarySocialLinksItem>
  >;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact section with contact information and form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: Contact section with contact information and form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *FeaturedArticles → Default → Primary*
 */
export interface FeaturedArticlesSliceDefaultPrimary {
  /**
   * Section Title field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Notícias em Destaque
   * - **API ID Path**: featured_articles.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: As principais notícias selecionadas pela redação...
   * - **API ID Path**: featured_articles.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;
}

/**
 * Default variation for FeaturedArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Featured articles section showing 4 articles in controlled order
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedArticles*
 */
type FeaturedArticlesSliceVariation = FeaturedArticlesSliceDefault;

/**
 * FeaturedArticles Shared Slice
 *
 * - **API ID**: `featured_articles`
 * - **Description**: Section displaying 4 featured news articles with controlled order
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedArticlesSlice = prismic.SharedSlice<
  "featured_articles",
  FeaturedArticlesSliceVariation
>;

/**
 * Primary content in *HeroAbout → Default → Primary*
 */
export interface HeroAboutSliceDefaultPrimary {
  /**
   * Title field in *HeroAbout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sobre Nós
   * - **API ID Path**: hero_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroAbout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Conheça nossa história e valores
   * - **API ID Path**: hero_about.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *HeroAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Uma breve descrição sobre a empresa...
   * - **API ID Path**: hero_about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeroAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero section with title, subtitle, description and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroAbout*
 */
type HeroAboutSliceVariation = HeroAboutSliceDefault;

/**
 * HeroAbout Shared Slice
 *
 * - **API ID**: `hero_about`
 * - **Description**: Hero section for About page with title, subtitle, description and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroAboutSlice = prismic.SharedSlice<
  "hero_about",
  HeroAboutSliceVariation
>;

/**
 * Item in *HeroStatsWithActions → Default → Primary → Statistics*
 */
export interface HeroStatsWithActionsSliceDefaultPrimaryStatsItem {
  /**
   * Stat Value field in *HeroStatsWithActions → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Stat Label field in *HeroStatsWithActions → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *HeroStatsWithActions → Default → Primary → Feature Cards*
 */
export interface HeroStatsWithActionsSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *HeroStatsWithActions → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Feature Heading field in *HeroStatsWithActions → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.features[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Feature Link field in *HeroStatsWithActions → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.features[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *HeroStatsWithActions → Default → Primary*
 */
export interface HeroStatsWithActionsSliceDefaultPrimary {
  /**
   * Title field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Main Media field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.main_media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_media: prismic.ImageField<never>;

  /**
   * Primary Call to Action field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Call to Action field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Statistics field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<
    Simplify<HeroStatsWithActionsSliceDefaultPrimaryStatsItem>
  >;

  /**
   * Feature Cards field in *HeroStatsWithActions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_stats_with_actions.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<HeroStatsWithActionsSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for HeroStatsWithActions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with headline, description, CTA buttons, image, stats, and a row of feature/action cards.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatsWithActionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroStatsWithActionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroStatsWithActions*
 */
type HeroStatsWithActionsSliceVariation = HeroStatsWithActionsSliceDefault;

/**
 * HeroStatsWithActions Shared Slice
 *
 * - **API ID**: `hero_stats_with_actions`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatsWithActionsSlice = prismic.SharedSlice<
  "hero_stats_with_actions",
  HeroStatsWithActionsSliceVariation
>;

/**
 * Item in *OurMission → Default → Primary → Goal Items*
 */
export interface OurMissionSliceDefaultPrimaryGoalItemItem {
  /**
   * Icon field in *OurMission → Default → Primary → Goal Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.goal_item[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *OurMission → Default → Primary → Goal Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título do objetivo
   * - **API ID Path**: our_mission.default.primary.goal_item[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurMission → Default → Primary → Goal Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do objetivo...
   * - **API ID Path**: our_mission.default.primary.goal_item[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *OurMission → Default → Primary*
 */
export interface OurMissionSliceDefaultPrimary {
  /**
   * Title field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nossa Missão
   * - **API ID Path**: our_mission.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Mission Title field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Missão
   * - **API ID Path**: our_mission.default.primary.mission_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_title: prismic.KeyTextField;

  /**
   * Mission Description field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da missão...
   * - **API ID Path**: our_mission.default.primary.mission_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mission_description: prismic.RichTextField;

  /**
   * Vision Title field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Visão
   * - **API ID Path**: our_mission.default.primary.vision_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_title: prismic.KeyTextField;

  /**
   * Vision Description field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da visão...
   * - **API ID Path**: our_mission.default.primary.vision_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  vision_description: prismic.RichTextField;

  /**
   * Goal Items field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.goal_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  goal_item: prismic.GroupField<
    Simplify<OurMissionSliceDefaultPrimaryGoalItemItem>
  >;
}

/**
 * Default variation for OurMission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Our Mission section with mission, vision and goals
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurMission*
 */
type OurMissionSliceVariation = OurMissionSliceDefault;

/**
 * OurMission Shared Slice
 *
 * - **API ID**: `our_mission`
 * - **Description**: Our Mission section with mission, vision and goals
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSlice = prismic.SharedSlice<
  "our_mission",
  OurMissionSliceVariation
>;

/**
 * Item in *OurStory → Default → Primary → Timeline Items*
 */
export interface OurStorySliceDefaultPrimaryTimelineItemItem {
  /**
   * Year field in *OurStory → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2020
   * - **API ID Path**: our_story.default.primary.timeline_item[].year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;

  /**
   * Title field in *OurStory → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título do marco
   * - **API ID Path**: our_story.default.primary.timeline_item[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurStory → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do marco histórico...
   * - **API ID Path**: our_story.default.primary.timeline_item[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *OurStory → Default → Primary → Timeline Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.timeline_item[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *OurStory → Default → Primary*
 */
export interface OurStorySliceDefaultPrimary {
  /**
   * Title field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nossa História
   * - **API ID Path**: our_story.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Uma breve introdução sobre nossa história...
   * - **API ID Path**: our_story.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Timeline Items field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.timeline_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline_item: prismic.GroupField<
    Simplify<OurStorySliceDefaultPrimaryTimelineItemItem>
  >;
}

/**
 * Default variation for OurStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Our Story section with timeline and milestones
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurStorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurStorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurStory*
 */
type OurStorySliceVariation = OurStorySliceDefault;

/**
 * OurStory Shared Slice
 *
 * - **API ID**: `our_story`
 * - **Description**: Our Story section with timeline and milestones
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurStorySlice = prismic.SharedSlice<
  "our_story",
  OurStorySliceVariation
>;

/**
 * Item in *OurValues → Default → Primary → Value Items*
 */
export interface OurValuesSliceDefaultPrimaryValueItemItem {
  /**
   * Icon field in *OurValues → Default → Primary → Value Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_values.default.primary.value_item[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *OurValues → Default → Primary → Value Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título do valor
   * - **API ID Path**: our_values.default.primary.value_item[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurValues → Default → Primary → Value Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do valor...
   * - **API ID Path**: our_values.default.primary.value_item[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *OurValues → Default → Primary*
 */
export interface OurValuesSliceDefaultPrimary {
  /**
   * Title field in *OurValues → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nossos Valores
   * - **API ID Path**: our_values.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurValues → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Uma breve introdução sobre nossos valores...
   * - **API ID Path**: our_values.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Value Items field in *OurValues → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_values.default.primary.value_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  value_item: prismic.GroupField<
    Simplify<OurValuesSliceDefaultPrimaryValueItemItem>
  >;
}

/**
 * Default variation for OurValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Our Values section with value cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurValuesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurValues*
 */
type OurValuesSliceVariation = OurValuesSliceDefault;

/**
 * OurValues Shared Slice
 *
 * - **API ID**: `our_values`
 * - **Description**: Our Values section with value cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurValuesSlice = prismic.SharedSlice<
  "our_values",
  OurValuesSliceVariation
>;

/**
 * Item in *PresentersTeam → Default → Primary → Presenters → Social Links*
 */
export interface PresentersTeamSliceDefaultPrimaryPresentersPresenterSocialLinksItem {
  /**
   * Social Platform field in *PresentersTeam → Default → Primary → Presenters → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Escolha a plataforma
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_social_links[].social_platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  social_platform: prismic.SelectField<
    | "Instagram"
    | "Twitter"
    | "LinkedIn"
    | "Facebook"
    | "YouTube"
    | "TikTok"
    | "Website"
  >;

  /**
   * Social URL field in *PresentersTeam → Default → Primary → Presenters → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL da rede social
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_social_links[].social_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *PresentersTeam → Default → Primary → Presenters*
 */
export interface PresentersTeamSliceDefaultPrimaryPresentersItem {
  /**
   * Presenter Name  field in *PresentersTeam → Default → Primary → Presenters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do Apresentador
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  presenter_name: prismic.KeyTextField;

  /**
   * Presenter Role field in *PresentersTeam → Default → Primary → Presenters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cargo/Função
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  presenter_role: prismic.KeyTextField;

  /**
   * Presenter Bio  field in *PresentersTeam → Default → Primary → Presenters*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Biografia do apresentador...
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  presenter_bio: prismic.RichTextField;

  /**
   * Presenter Photo  field in *PresentersTeam → Default → Primary → Presenters*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  presenter_photo: prismic.ImageField<never>;

  /**
   * Social Links field in *PresentersTeam → Default → Primary → Presenters*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: presenters_team.default.primary.presenters[].presenter_social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  presenter_social_links: prismic.NestedGroupField<
    Simplify<PresentersTeamSliceDefaultPrimaryPresentersPresenterSocialLinksItem>
  >;
}

/**
 * Primary content in *PresentersTeam → Default → Primary*
 */
export interface PresentersTeamSliceDefaultPrimary {
  /**
   * Title  field in *PresentersTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nossa Equipe
   * - **API ID Path**: presenters_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PresentersTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Conheça os apresentadores...
   * - **API ID Path**: presenters_team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Presenters field in *PresentersTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: presenters_team.default.primary.presenters[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  presenters: prismic.GroupField<
    Simplify<PresentersTeamSliceDefaultPrimaryPresentersItem>
  >;
}

/**
 * Default variation for PresentersTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PresentersTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PresentersTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PresentersTeam*
 */
type PresentersTeamSliceVariation = PresentersTeamSliceDefault;

/**
 * PresentersTeam Shared Slice
 *
 * - **API ID**: `presenters_team`
 * - **Description**: PresentersTeam
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PresentersTeamSlice = prismic.SharedSlice<
  "presenters_team",
  PresentersTeamSliceVariation
>;

/**
 * Item in *ProgramsList → Default → Primary → Program*
 */
export interface ProgramsListSliceDefaultPrimaryProgramItem {
  /**
   * Program Title field in *ProgramsList → Default → Primary → Program*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.program[].program_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  program_title: prismic.KeyTextField;

  /**
   * Program Description field in *ProgramsList → Default → Primary → Program*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.program[].program_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  program_description: prismic.RichTextField;

  /**
   * Program Image field in *ProgramsList → Default → Primary → Program*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.program[].program_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  program_image: prismic.ImageField<never>;

  /**
   * Program episodes list field in *ProgramsList → Default → Primary → Program*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.program[].program_episodes_list
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  program_episodes_list: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ProgramsList → Default → Primary*
 */
export interface ProgramsListSliceDefaultPrimary {
  /**
   * title field in *ProgramsList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *ProgramsList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Program field in *ProgramsList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: programs_list.default.primary.program[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  program: prismic.GroupField<
    Simplify<ProgramsListSliceDefaultPrimaryProgramItem>
  >;
}

/**
 * Default variation for ProgramsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramsListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgramsListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProgramsList*
 */
type ProgramsListSliceVariation = ProgramsListSliceDefault;

/**
 * ProgramsList Shared Slice
 *
 * - **API ID**: `programs_list`
 * - **Description**: ProgramsList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramsListSlice = prismic.SharedSlice<
  "programs_list",
  ProgramsListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      JuncoNewsDocument,
      JuncoNewsDocumentData,
      JuncoNewsDocumentDataSlicesSlice,
      NewsArticleDocument,
      NewsArticleDocumentData,
      AllDocumentTypes,
      ArticlesGridSlice,
      ArticlesGridSliceDefaultPrimaryFilterCategoriesItem,
      ArticlesGridSliceDefaultPrimary,
      ArticlesGridSliceVariation,
      ArticlesGridSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimarySocialLinksItem,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      FeaturedArticlesSlice,
      FeaturedArticlesSliceDefaultPrimary,
      FeaturedArticlesSliceVariation,
      FeaturedArticlesSliceDefault,
      HeroAboutSlice,
      HeroAboutSliceDefaultPrimary,
      HeroAboutSliceVariation,
      HeroAboutSliceDefault,
      HeroStatsWithActionsSlice,
      HeroStatsWithActionsSliceDefaultPrimaryStatsItem,
      HeroStatsWithActionsSliceDefaultPrimaryFeaturesItem,
      HeroStatsWithActionsSliceDefaultPrimary,
      HeroStatsWithActionsSliceVariation,
      HeroStatsWithActionsSliceDefault,
      OurMissionSlice,
      OurMissionSliceDefaultPrimaryGoalItemItem,
      OurMissionSliceDefaultPrimary,
      OurMissionSliceVariation,
      OurMissionSliceDefault,
      OurStorySlice,
      OurStorySliceDefaultPrimaryTimelineItemItem,
      OurStorySliceDefaultPrimary,
      OurStorySliceVariation,
      OurStorySliceDefault,
      OurValuesSlice,
      OurValuesSliceDefaultPrimaryValueItemItem,
      OurValuesSliceDefaultPrimary,
      OurValuesSliceVariation,
      OurValuesSliceDefault,
      PresentersTeamSlice,
      PresentersTeamSliceDefaultPrimaryPresentersPresenterSocialLinksItem,
      PresentersTeamSliceDefaultPrimaryPresentersItem,
      PresentersTeamSliceDefaultPrimary,
      PresentersTeamSliceVariation,
      PresentersTeamSliceDefault,
      ProgramsListSlice,
      ProgramsListSliceDefaultPrimaryProgramItem,
      ProgramsListSliceDefaultPrimary,
      ProgramsListSliceVariation,
      ProgramsListSliceDefault,
    };
  }
}
