// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_stats_with_actions: dynamic(() => import("./HeroStatsWithActions")),
  presenters_team: dynamic(() => import("./PresentersTeam")),
  programs_list: dynamic(() => import("./ProgramsList")),
  featured_articles: dynamic(() => import("./FeaturedArticles")),
  articles_grid: dynamic(() => import("./ArticlesGrid")),
  hero_about: dynamic(() => import("./HeroAbout")),
  our_story: dynamic(() => import("./OurStory")),
  our_values: dynamic(() => import("./OurValues")),
  our_mission: dynamic(() => import("./OurMission")),
  contact_section: dynamic(() => import("./ContactSection")),
};
